### PR TITLE
New charts

### PR DESCRIPTION
**Pull request by AkinariHex**
This PR will address a lot of bugs regarding the charts in the dashboard/user page.
There was a plan for a new chart that for now is in standby/not gonna be used for now.

- [x] #170 
- [x] #187 
- [x] #154 
- [x] #86 

This contain other fixes to layout and adding bunch of new UI that were added in the figma design.

Requires the new changes from otr-api about the change from `worstTournamentPerformances` to `recentTournamentPerformances`

### Todo
- [x] Change color for line bar graphs
- [ ] Add tooltip in some graphs

### CODE REVIEW

**Comment by hburn7** [comment]
#170 & #86 look good enough for beta.

**Comment by hburn7** [comment]
@AkinariHex Is this still being worked on? I'd like to get this out of a draft state.

**Comment by hburn7** [comment]
I think this mostly looks good, a few points of feedback:

- All bar charts need to have padding on the end. It seems like some charts have the padding depending on the profile you are browsing. My profile, bento's profile, and cytusine's profile all have charts that fill up the entire chart with no padding. Some charts do not have padding regardless of which profile is being browsed. Ensure all charts on all profiles have the proper padding before merging.
- If possible, I would really like to see the rounded profile pictures before merging.

Figma:
image

Website (my profile):
image

**Comment by hburn7** [comment]
Additionally, is there a way to fix this missing line? Why does it go from 1.8 to 2.1? (worst hr player)
image

**Comment by AkinariHex** [comment]
> Additionally, is there a way to fix this missing line? Why does it go from 1.8 to 2.1? (worst hr player) image

For this one, I was pretty sure I made a fix for this problem, and with the data I had it was working, I will check it again

**Comment by AkinariHex** [comment]
For charts without padding and without rounded images I will try to do my best to implement before merge

**Review by hburn7 — APPROVED** [review]

**Comment by hburn7** [comment]
Looks great.

**Pull request merged**
